"""
Enumerations for the Registry Defect Engine domain model.

These enums are the controlled vocabularies referenced throughout the
system. They intentionally include UNKNOWN / UNVERIFIED members almost
everywhere a determination cannot be made automatically — the engine
must be able to say "I don't know" rather than guessing.
"""
from enum import Enum


class RequirementSourceType(str, Enum):
    SOURCE_DOCUMENT = "SOURCE_DOCUMENT"
    USER_PROVIDED_CHECKLIST = "USER_PROVIDED_CHECKLIST"
    AUTHORIZED_TEMPLATE = "AUTHORIZED_TEMPLATE"
    CONFIGURED_REGISTRY_RULE = "CONFIGURED_REGISTRY_RULE"
    IMPORTED_REQUIREMENT_SET = "IMPORTED_REQUIREMENT_SET"
    UNKNOWN = "UNKNOWN"


class RequirementStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUPERSEDED = "SUPERSEDED"
    UNKNOWN = "UNKNOWN"
    REQUIRES_VERIFICATION = "REQUIRES_VERIFICATION"


class RequirementType(str, Enum):
    DOCUMENT_REQUIRED = "DOCUMENT_REQUIRED"
    ATTACHMENT_REQUIRED = "ATTACHMENT_REQUIRED"
    FIELD_REQUIRED = "FIELD_REQUIRED"
    METADATA_REQUIRED = "METADATA_REQUIRED"
    FORMAT_REQUIRED = "FORMAT_REQUIRED"
    REFERENCE_REQUIRED = "REFERENCE_REQUIRED"
    SIGNATURE_REQUIRED_WHEN_EXPLICITLY_SPECIFIED = "SIGNATURE_REQUIRED_WHEN_EXPLICITLY_SPECIFIED"
    CHECKLIST_ITEM = "CHECKLIST_ITEM"
    CUSTOM = "CUSTOM"
    UNKNOWN = "UNKNOWN"


class VerificationStatus(str, Enum):
    KNOWN = "KNOWN"
    SOURCE_SUPPORTED = "SOURCE_SUPPORTED"
    USER_REPORTED = "USER_REPORTED"
    SYSTEM_DETECTED = "SYSTEM_DETECTED"
    UNVERIFIED = "UNVERIFIED"
    CONFLICTING = "CONFLICTING"
    UNKNOWN = "UNKNOWN"
    REQUIRES_HUMAN_REVIEW = "REQUIRES_HUMAN_REVIEW"


class ChecklistItemStatus(str, Enum):
    FOUND = "FOUND"
    MISSING = "MISSING"
    PARTIAL = "PARTIAL"
    CONFLICTING = "CONFLICTING"
    UNVERIFIED = "UNVERIFIED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    UNKNOWN = "UNKNOWN"
    REQUIRES_HUMAN_REVIEW = "REQUIRES_HUMAN_REVIEW"


class FilingLifecycleState(str, Enum):
    DRAFT = "DRAFT"
    PACKAGE_ASSEMBLED = "PACKAGE_ASSEMBLED"
    PRECHECK = "PRECHECK"
    DEFECTS_DETECTED = "DEFECTS_DETECTED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    READY_FOR_HUMAN_REVIEW = "READY_FOR_HUMAN_REVIEW"
    APPROVED_FOR_SUBMISSION = "APPROVED_FOR_SUBMISSION"
    SUBMITTED = "SUBMITTED"
    REGISTRY_FEEDBACK_RECEIVED = "REGISTRY_FEEDBACK_RECEIVED"
    CORRECTION_REQUIRED = "CORRECTION_REQUIRED"
    CORRECTION_SUBMITTED = "CORRECTION_SUBMITTED"
    RESUBMISSION_REVIEW = "RESUBMISSION_REVIEW"
    CLOSED = "CLOSED"
    BLOCKED = "BLOCKED"
    CONFLICTING = "CONFLICTING"
    UNKNOWN = "UNKNOWN"
    CANCELLED = "CANCELLED"
    SUPERSEDED = "SUPERSEDED"


class DocumentQualityIssue(str, Enum):
    EMPTY_DOCUMENT = "EMPTY_DOCUMENT"
    UNREADABLE_DOCUMENT = "UNREADABLE_DOCUMENT"
    PARSER_FAILURE = "PARSER_FAILURE"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    CORRUPTED_DOCUMENT = "CORRUPTED_DOCUMENT"
    DUPLICATE_DOCUMENT = "DUPLICATE_DOCUMENT"
    POSSIBLE_DUPLICATE = "POSSIBLE_DUPLICATE"
    MISSING_METADATA = "MISSING_METADATA"
    INCONSISTENT_METADATA = "INCONSISTENT_METADATA"
    VERSION_AMBIGUITY = "VERSION_AMBIGUITY"
    SUPERSEDED_DOCUMENT = "SUPERSEDED_DOCUMENT"
    MISSING_SOURCE_REFERENCE = "MISSING_SOURCE_REFERENCE"


class DefectType(str, Enum):
    # Completeness
    MISSING_DOCUMENT = "MISSING_DOCUMENT"
    MISSING_ATTACHMENT = "MISSING_ATTACHMENT"
    MISSING_REFERENCED_ITEM = "MISSING_REFERENCED_ITEM"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    PARTIAL_PACKAGE = "PARTIAL_PACKAGE"
    # Document quality
    UNREADABLE = "UNREADABLE"
    CORRUPTED = "CORRUPTED"
    EMPTY = "EMPTY"
    PARSER_FAILURE = "PARSER_FAILURE"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    # Metadata
    METADATA_MISSING = "METADATA_MISSING"
    METADATA_CONFLICT = "METADATA_CONFLICT"
    IDENTIFIER_MISMATCH = "IDENTIFIER_MISMATCH"
    DATE_CONFLICT = "DATE_CONFLICT"
    PARTY_NAME_CONFLICT = "PARTY_NAME_CONFLICT"
    # Version
    POSSIBLE_OLD_VERSION = "POSSIBLE_OLD_VERSION"
    DUPLICATE_VERSION = "DUPLICATE_VERSION"
    SUPERSEDED_DOCUMENT = "SUPERSEDED_DOCUMENT"
    VERSION_AMBIGUITY = "VERSION_AMBIGUITY"
    # Registry feedback
    UNRESOLVED_OBJECTION = "UNRESOLVED_OBJECTION"
    CORRECTION_REQUIRED = "CORRECTION_REQUIRED"
    CORRECTION_INCOMPLETE = "CORRECTION_INCOMPLETE"
    RESUBMISSION_PENDING = "RESUBMISSION_PENDING"
    # Reference integrity
    BROKEN_ATTACHMENT_REFERENCE = "BROKEN_ATTACHMENT_REFERENCE"
    BROKEN_DOCUMENT_REFERENCE = "BROKEN_DOCUMENT_REFERENCE"
    MISSING_CROSS_REFERENCE = "MISSING_CROSS_REFERENCE"
    # Provenance
    SOURCE_UNKNOWN = "SOURCE_UNKNOWN"
    HASH_MISSING = "HASH_MISSING"
    PROVENANCE_GAP = "PROVENANCE_GAP"
    SOURCE_LOCATION_UNKNOWN = "SOURCE_LOCATION_UNKNOWN"
    # Security
    MALICIOUS_FILE = "MALICIOUS_FILE"
    SUSPICIOUS_CONTENT = "SUSPICIOUS_CONTENT"
    PROMPT_INJECTION_CONTENT = "PROMPT_INJECTION_CONTENT"


DEFECT_CATEGORY_MAP = {
    DefectType.MISSING_DOCUMENT: "COMPLETENESS",
    DefectType.MISSING_ATTACHMENT: "COMPLETENESS",
    DefectType.MISSING_REFERENCED_ITEM: "COMPLETENESS",
    DefectType.MISSING_REQUIRED_FIELD: "COMPLETENESS",
    DefectType.PARTIAL_PACKAGE: "COMPLETENESS",
    DefectType.UNREADABLE: "DOCUMENT_QUALITY",
    DefectType.CORRUPTED: "DOCUMENT_QUALITY",
    DefectType.EMPTY: "DOCUMENT_QUALITY",
    DefectType.PARSER_FAILURE: "DOCUMENT_QUALITY",
    DefectType.UNSUPPORTED_FORMAT: "DOCUMENT_QUALITY",
    DefectType.METADATA_MISSING: "METADATA",
    DefectType.METADATA_CONFLICT: "METADATA",
    DefectType.IDENTIFIER_MISMATCH: "METADATA",
    DefectType.DATE_CONFLICT: "METADATA",
    DefectType.PARTY_NAME_CONFLICT: "METADATA",
    DefectType.POSSIBLE_OLD_VERSION: "VERSION",
    DefectType.DUPLICATE_VERSION: "VERSION",
    DefectType.SUPERSEDED_DOCUMENT: "VERSION",
    DefectType.VERSION_AMBIGUITY: "VERSION",
    DefectType.UNRESOLVED_OBJECTION: "REGISTRY_FEEDBACK",
    DefectType.CORRECTION_REQUIRED: "REGISTRY_FEEDBACK",
    DefectType.CORRECTION_INCOMPLETE: "REGISTRY_FEEDBACK",
    DefectType.RESUBMISSION_PENDING: "REGISTRY_FEEDBACK",
    DefectType.BROKEN_ATTACHMENT_REFERENCE: "REFERENCE_INTEGRITY",
    DefectType.BROKEN_DOCUMENT_REFERENCE: "REFERENCE_INTEGRITY",
    DefectType.MISSING_CROSS_REFERENCE: "REFERENCE_INTEGRITY",
    DefectType.SOURCE_UNKNOWN: "PROVENANCE",
    DefectType.HASH_MISSING: "PROVENANCE",
    DefectType.PROVENANCE_GAP: "PROVENANCE",
    DefectType.SOURCE_LOCATION_UNKNOWN: "PROVENANCE",
    DefectType.MALICIOUS_FILE: "SECURITY",
    DefectType.SUSPICIOUS_CONTENT: "SECURITY",
    DefectType.PROMPT_INJECTION_CONTENT: "SECURITY",
}


class DefectSeverity(str, Enum):
    """Operational attention level. NOT a legal severity judgment."""
    INFO = "INFO"
    ATTENTION = "ATTENTION"
    HIGH_ATTENTION = "HIGH_ATTENTION"
    REQUIRES_HUMAN_REVIEW = "REQUIRES_HUMAN_REVIEW"


class DefectLifecycleState(str, Enum):
    DETECTED = "DETECTED"
    TRIAGED = "TRIAGED"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    CONFIRMED = "CONFIRMED"
    ACTION_REQUIRED = "ACTION_REQUIRED"
    CORRECTION_SUBMITTED = "CORRECTION_SUBMITTED"
    VERIFIED = "VERIFIED"
    RESOLVED = "RESOLVED"
    REJECTED = "REJECTED"
    FALSE_POSITIVE = "FALSE_POSITIVE"
    DUPLICATE = "DUPLICATE"
    UNKNOWN = "UNKNOWN"
    BLOCKED = "BLOCKED"


class ObjectionStatus(str, Enum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    CORRECTION_PLANNED = "CORRECTION_PLANNED"
    CORRECTION_SUBMITTED = "CORRECTION_SUBMITTED"
    VERIFICATION_PENDING = "VERIFICATION_PENDING"
    RESOLVED = "RESOLVED"


class VersionRelationship(str, Enum):
    SUPERSEDES = "SUPERSEDES"
    SUPERSEDED_BY = "SUPERSEDED_BY"
    REVISION_OF = "REVISION_OF"
    DUPLICATE_OF = "DUPLICATE_OF"
    UNKNOWN_RELATIONSHIP = "UNKNOWN_RELATIONSHIP"


class DuplicateType(str, Enum):
    EXACT_DUPLICATE = "EXACT_DUPLICATE"
    HASH_DUPLICATE = "HASH_DUPLICATE"
    POSSIBLE_CONTENT_DUPLICATE = "POSSIBLE_CONTENT_DUPLICATE"
    POSSIBLE_VERSION_DUPLICATE = "POSSIBLE_VERSION_DUPLICATE"


class ActionProposalType(str, Enum):
    REQUEST_MISSING_DOCUMENT = "REQUEST_MISSING_DOCUMENT"
    REQUEST_CLARIFICATION = "REQUEST_CLARIFICATION"
    REPLACE_DOCUMENT_VERSION = "REPLACE_DOCUMENT_VERSION"
    ATTACH_MISSING_REFERENCE = "ATTACH_MISSING_REFERENCE"
    VERIFY_METADATA = "VERIFY_METADATA"
    REVIEW_CONFLICT = "REVIEW_CONFLICT"
    VERIFY_REQUIREMENT = "VERIFY_REQUIREMENT"
    RESPOND_TO_OBJECTION = "RESPOND_TO_OBJECTION"
    RECHECK_PACKAGE = "RECHECK_PACKAGE"


class UserRole(str, Enum):
    CITIZEN = "CITIZEN"
    LEGAL_AID = "LEGAL_AID"
    ADVOCATE = "ADVOCATE"
    ADMIN = "ADMIN"


class ReviewDecision(str, Enum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PENDING = "PENDING"


class DocumentFormat(str, Enum):
    PDF = "PDF"
    DOCX = "DOCX"
    TXT = "TXT"
    JSON = "JSON"
    CSV = "CSV"
    UNSUPPORTED = "UNSUPPORTED"


SOURCE_LOCATION_UNKNOWN = "SOURCE_LOCATION_UNKNOWN"
REQUIREMENT_UNKNOWN = "REQUIREMENT_UNKNOWN"
