"""
Shared enumerations for CASE CRASH TEST & RESILIENCE LAB.

These enums are the vocabulary of the entire engine. Nothing in this file
represents a legal outcome, a judicial prediction, or a legal rule. They
describe GRAPH STRUCTURE and OPERATIONAL STATE only.
"""

from enum import Enum


class NodeType(str, Enum):
    DOCUMENT = "DOCUMENT"
    EVIDENCE = "EVIDENCE"
    CLAIM = "CLAIM"
    ISSUE = "ISSUE"
    OBLIGATION = "OBLIGATION"
    DEADLINE = "DEADLINE"
    HEARING = "HEARING"
    ORDER = "ORDER"
    FILING_PACKAGE = "FILING_PACKAGE"
    REGISTRY_DEFECT = "REGISTRY_DEFECT"
    CUSTODY_EVENT = "CUSTODY_EVENT"
    WORKFLOW = "WORKFLOW"
    ACTION = "ACTION"
    VERIFICATION = "VERIFICATION"


class RelationshipType(str, Enum):
    SUPPORTS = "SUPPORTS"
    DEPENDS_ON = "DEPENDS_ON"
    REQUIRES = "REQUIRES"
    BLOCKS = "BLOCKS"
    AFFECTS = "AFFECTS"
    DERIVED_FROM = "DERIVED_FROM"
    SUPERSEDES = "SUPERSEDES"
    SUPERSEDED_BY = "SUPERSEDED_BY"
    CONTRADICTS = "CONTRADICTS"
    CORROBORATES = "CORROBORATES"
    REFERENCES = "REFERENCES"
    TRIGGERS = "TRIGGERS"
    VERIFIED_BY = "VERIFIED_BY"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"
    UNKNOWN_RELATIONSHIP = "UNKNOWN_RELATIONSHIP"


# Relationship types that propagation treats as "dependency-carrying":
# if the SOURCE of one of these edges is disturbed, the TARGET may be affected.
# e.g. Claim -[DEPENDS_ON]-> Evidence: if Evidence is disturbed, Claim is affected.
PROPAGATING_RELATIONSHIPS = {
    RelationshipType.DEPENDS_ON,
    RelationshipType.REQUIRES,
    RelationshipType.SUPPORTS,       # reverse direction handled in traversal
    RelationshipType.VERIFIED_BY,
    RelationshipType.TRIGGERS,
    RelationshipType.BLOCKS,
}


class NodeStatus(str, Enum):
    KNOWN = "KNOWN"
    VERIFIED = "VERIFIED"
    UNVERIFIED = "UNVERIFIED"
    UNKNOWN = "UNKNOWN"
    CONFLICTING = "CONFLICTING"
    BLOCKED = "BLOCKED"
    SUPERSEDED = "SUPERSEDED"
    EXCLUDED = "EXCLUDED"
    MISSING = "MISSING"
    REQUIRES_HUMAN_REVIEW = "REQUIRES_HUMAN_REVIEW"


class ImpactType(str, Enum):
    """
    Structural impact labels used to describe WHAT KIND of downstream effect
    a node experienced during propagation. These are graph-derived labels,
    never legal conclusions.
    """
    SUPPORT_GAP = "SUPPORT_GAP"
    VERIFICATION_GAP = "VERIFICATION_GAP"
    NEW_CONFLICT = "NEW_CONFLICT"
    NEW_UNKNOWN = "NEW_UNKNOWN"
    NEWLY_BLOCKED = "NEWLY_BLOCKED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    NO_IMPACT = "NO_IMPACT"


class CriticalityLabel(str, Enum):
    """Structural criticality only. NOT legal importance."""
    ISOLATED = "ISOLATED"
    LOW_DEPENDENCY = "LOW_DEPENDENCY"
    MULTI_DEPENDENCY = "MULTI_DEPENDENCY"
    HIGH_DEPENDENCY = "HIGH_DEPENDENCY"
    SINGLE_POINT_DEPENDENCY = "SINGLE_POINT_DEPENDENCY"


class MutationType(str, Enum):
    # Evidence
    REMOVE_EVIDENCE = "REMOVE_EVIDENCE"
    EXCLUDE_EVIDENCE = "EXCLUDE_EVIDENCE"
    MARK_EVIDENCE_UNVERIFIED = "MARK_EVIDENCE_UNVERIFIED"
    INVALIDATE_PROVENANCE = "INVALIDATE_PROVENANCE"
    CONTRADICT_EVIDENCE = "CONTRADICT_EVIDENCE"
    SUPERSEDE_EVIDENCE = "SUPERSEDE_EVIDENCE"
    # Document
    REMOVE_DOCUMENT = "REMOVE_DOCUMENT"
    CORRUPT_DOCUMENT = "CORRUPT_DOCUMENT"
    SUPERSEDE_DOCUMENT = "SUPERSEDE_DOCUMENT"
    REPLACE_DOCUMENT_VERSION = "REPLACE_DOCUMENT_VERSION"
    MAKE_DOCUMENT_UNAVAILABLE = "MAKE_DOCUMENT_UNAVAILABLE"
    # Claim
    REMOVE_CLAIM = "REMOVE_CLAIM"
    CONTRADICT_CLAIM = "CONTRADICT_CLAIM"
    MARK_CLAIM_UNVERIFIED = "MARK_CLAIM_UNVERIFIED"
    BREAK_CLAIM_DEPENDENCY = "BREAK_CLAIM_DEPENDENCY"
    # Issue
    REMOVE_ISSUE_SUPPORT = "REMOVE_ISSUE_SUPPORT"
    CREATE_ISSUE_CONFLICT = "CREATE_ISSUE_CONFLICT"
    MARK_ISSUE_UNKNOWN = "MARK_ISSUE_UNKNOWN"
    # Obligation
    BLOCK_OBLIGATION = "BLOCK_OBLIGATION"
    REMOVE_OBLIGATION_EVIDENCE = "REMOVE_OBLIGATION_EVIDENCE"
    MARK_OBLIGATION_UNVERIFIED = "MARK_OBLIGATION_UNVERIFIED"
    SUPERSEDE_OBLIGATION = "SUPERSEDE_OBLIGATION"
    CREATE_OBLIGATION_CONFLICT = "CREATE_OBLIGATION_CONFLICT"
    # Deadline
    REMOVE_TRACKED_DATE = "REMOVE_TRACKED_DATE"
    CHANGE_USER_ENTERED_DATE = "CHANGE_USER_ENTERED_DATE"
    MARK_DATE_UNKNOWN = "MARK_DATE_UNKNOWN"
    CREATE_DATE_CONFLICT = "CREATE_DATE_CONFLICT"
    # Hearing
    REMOVE_HEARING_RESULT = "REMOVE_HEARING_RESULT"
    MARK_HEARING_UNVERIFIED = "MARK_HEARING_UNVERIFIED"
    CHANGE_SOURCE_STATED_HEARING_DATE = "CHANGE_SOURCE_STATED_HEARING_DATE"
    REMOVE_HEARING_DOCUMENT = "REMOVE_HEARING_DOCUMENT"
    # Order
    SUPERSEDE_ORDER = "SUPERSEDE_ORDER"
    REMOVE_ORDER_SOURCE = "REMOVE_ORDER_SOURCE"
    MARK_ORDER_UNVERIFIED = "MARK_ORDER_UNVERIFIED"
    CREATE_ORDER_CONFLICT = "CREATE_ORDER_CONFLICT"
    # Registry
    INTRODUCE_DEFECT = "INTRODUCE_DEFECT"
    REMOVE_REQUIRED_DOCUMENT = "REMOVE_REQUIRED_DOCUMENT"
    CREATE_METADATA_CONFLICT = "CREATE_METADATA_CONFLICT"
    CREATE_MISSING_REFERENCE = "CREATE_MISSING_REFERENCE"
    LEAVE_OBJECTION_UNRESOLVED = "LEAVE_OBJECTION_UNRESOLVED"
    # Custody / Liberty
    MARK_CUSTODY_EVENT_UNVERIFIED = "MARK_CUSTODY_EVENT_UNVERIFIED"
    CREATE_CUSTODY_CONFLICT = "CREATE_CUSTODY_CONFLICT"
    REMOVE_CUSTODY_DOCUMENT = "REMOVE_CUSTODY_DOCUMENT"
    REMOVE_RELEASE_EVENT_SOURCE = "REMOVE_RELEASE_EVENT_SOURCE"
    # Workflow
    BLOCK_ACTION = "BLOCK_ACTION"
    REMOVE_ACTION_DEPENDENCY = "REMOVE_ACTION_DEPENDENCY"
    ACTION_FAILURE = "ACTION_FAILURE"
    VERIFICATION_FAILURE = "VERIFICATION_FAILURE"
    APPROVAL_MISSING = "APPROVAL_MISSING"
    # Provenance
    INVALIDATE_SOURCE = "INVALIDATE_SOURCE"
    REMOVE_SOURCE_REFERENCE = "REMOVE_SOURCE_REFERENCE"
    BREAK_PROVENANCE_CHAIN = "BREAK_PROVENANCE_CHAIN"


class SimulationStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ReviewStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
