"""
Context Packaging Agent (sec 27), Handoff Review Agent (sec 28),
Context Loss Agent (sec 29).

Each agent run is recorded as an AgentRun row (auditable), and each
narrative note is generated by the LLMProvider abstraction (mock by
default — see llm_provider.py) layered ON TOP OF deterministic engine
output. The agents never invent facts themselves: they only narrate or
critique what the rule-based engines already computed.
"""
import time
from sqlalchemy.orm import Session

from models import Case, Role, HandoffVersion, AgentRun
from handoff.generator import generate_packet
from verification.context_loss import compare_source_to_handoff
from agents.llm_provider import get_provider


def _record_run(db: Session, case_id: str, agent_name: str, input_summary: str, output_summary: str,
                 provider: str, latency_ms: int, correlation_id: str = None) -> AgentRun:
    run = AgentRun(case_id=case_id, agent_name=agent_name, input_summary=input_summary,
                    output_summary=output_summary, provider=provider, latency_ms=latency_ms,
                    correlation_id=correlation_id)
    db.add(run)
    db.commit()
    db.refresh(run)
    return run


def context_packaging_agent(db: Session, case: Case, purpose: str, recipient_role: Role,
                             sender_role: Role, version_number: int = 1) -> HandoffVersion:
    t0 = time.time()
    version = generate_packet(db, case, purpose, recipient_role, sender_role, version_number)
    provider = get_provider()
    result = provider.complete(
        system="You propose a role-appropriate legal-aid handoff packet from structured case data.",
        prompt=f"Case {case.id}: purpose={purpose}, recipient={recipient_role.value}, "
               f"included_facts={len(version.included_fact_ids)}",
    )
    _record_run(db, case.id, "ContextPackagingAgent",
                input_summary=f"purpose={purpose} recipient={recipient_role.value}",
                output_summary=f"packet v{version.version_number}, overall={version.quality_checks.get('overall')}",
                provider=result.provider, latency_ms=result.latency_ms)
    return version


def handoff_review_agent(db: Session, case: Case, version: HandoffVersion) -> dict:
    """Independently challenges the proposed packet (sec 28)."""
    findings = []
    checks = version.quality_checks or {}
    for name, c in checks.items():
        if name == "overall":
            continue
        if not c.get("pass", True):
            findings.append(f"CHALLENGE: {name} failed — {c.get('detail')}")
    if version.risk_flags:
        for r in version.risk_flags:
            findings.append(f"RISK NOTED: {r['risk']} — {r['detail']}")
    if not findings:
        findings.append("No objections — packet appears complete for the stated purpose and recipient.")

    provider = get_provider()
    result = provider.complete(
        system="You independently review a proposed legal-aid handoff packet for gaps or overreach.",
        prompt=f"Packet checks: {checks}",
    )
    _record_run(db, case.id, "HandoffReviewAgent",
                input_summary=f"handoff_version={version.id}",
                output_summary="; ".join(findings)[:500],
                provider=result.provider, latency_ms=result.latency_ms)
    return {"findings": findings, "recommendation": "APPROVE" if checks.get("overall") == "READY_FOR_REVIEW"
            else ("REJECT" if checks.get("overall") == "BLOCKED" else "APPROVE_WITH_CAUTION")}


def context_loss_agent(db: Session, case: Case, version: HandoffVersion) -> dict:
    result_data = compare_source_to_handoff(db, case, version)
    provider = get_provider()
    result = provider.complete(
        system="You summarize a structured context-loss comparison for a human reviewer.",
        prompt=f"Loss report: {result_data}",
    )
    _record_run(db, case.id, "ContextLossAgent",
                input_summary=f"handoff_version={version.id}",
                output_summary=f"context_loss_detected={result_data['context_loss_detected']}",
                provider=result.provider, latency_ms=result.latency_ms)
    return result_data
