"""
Core enumerations for SPARK Workflow Autopilot.
These are the closed vocabularies the whole engine is built on.
"""
import enum


class WorkflowState(str, enum.Enum):
    DRAFT = "DRAFT"
    PLANNED = "PLANNED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    APPROVED = "APPROVED"
    READY = "READY"
    RUNNING = "RUNNING"
    WAITING = "WAITING"
    BLOCKED = "BLOCKED"
    PARTIALLY_COMPLETED = "PARTIALLY_COMPLETED"
    VERIFICATION_PENDING = "VERIFICATION_PENDING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    SUPERSEDED = "SUPERSEDED"
    UNKNOWN = "UNKNOWN"


class TaskState(str, enum.Enum):
    TODO = "TODO"
    READY = "READY"
    IN_PROGRESS = "IN_PROGRESS"
    WAITING = "WAITING"
    BLOCKED = "BLOCKED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    COMPLETED = "COMPLETED"
    VERIFICATION_PENDING = "VERIFICATION_PENDING"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class RiskLevel(str, enum.Enum):
    SAFE_REVERSIBLE = "SAFE_REVERSIBLE"
    LOW_RISK = "LOW_RISK"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    CONSEQUENTIAL = "CONSEQUENTIAL"
    FORBIDDEN_AUTOMATION = "FORBIDDEN_AUTOMATION"


class TriggerType(str, enum.Enum):
    CASE_CHANGED = "CASE_CHANGED"
    NEW_EVIDENCE_GAP = "NEW_EVIDENCE_GAP"
    OBLIGATION_CREATED = "OBLIGATION_CREATED"
    OBLIGATION_BLOCKED = "OBLIGATION_BLOCKED"
    TRACKED_DATE_APPROACHING = "TRACKED_DATE_APPROACHING"
    PAST_TRACKED_DATE = "PAST_TRACKED_DATE"
    REGISTRY_DEFECT_DETECTED = "REGISTRY_DEFECT_DETECTED"
    HEARING_READINESS_BLOCKER = "HEARING_READINESS_BLOCKER"
    CASE_BOTTLENECK_DETECTED = "CASE_BOTTLENECK_DETECTED"
    HANDOFF_REQUIRED = "HANDOFF_REQUIRED"
    VERIFICATION_PENDING = "VERIFICATION_PENDING"
    CONFLICT_DETECTED = "CONFLICT_DETECTED"
    PROVENANCE_GAP = "PROVENANCE_GAP"
    USER_CREATED_WORKFLOW = "USER_CREATED_WORKFLOW"
    MANUAL_TRIGGER = "MANUAL_TRIGGER"


class ApprovalState(str, enum.Enum):
    NOT_REQUIRED = "NOT_REQUIRED"
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"


class VerificationState(str, enum.Enum):
    NOT_REQUIRED = "NOT_REQUIRED"
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"


class Role(str, enum.Enum):
    CITIZEN = "CITIZEN"
    LEGAL_AID = "LEGAL_AID"
    PARALEGAL = "PARALEGAL"
    ADVOCATE = "ADVOCATE"
    ADMIN = "ADMIN"


class EventType(str, enum.Enum):
    WORKFLOW_CREATED = "WORKFLOW_CREATED"
    TASK_CREATED = "TASK_CREATED"
    TASK_READY = "TASK_READY"
    TASK_BLOCKED = "TASK_BLOCKED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_GRANTED = "APPROVAL_GRANTED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    VERIFICATION_REQUESTED = "VERIFICATION_REQUESTED"
    VERIFICATION_COMPLETED = "VERIFICATION_COMPLETED"
    WORKFLOW_BLOCKED = "WORKFLOW_BLOCKED"
    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"
    WORKFLOW_FAILED = "WORKFLOW_FAILED"
    CONFLICT_DETECTED = "CONFLICT_DETECTED"
    STALE_STATE_DETECTED = "STALE_STATE_DETECTED"
    RECOVERY_CHOSEN = "RECOVERY_CHOSEN"


# Terminal states — a workflow/task in one of these never transitions again.
WORKFLOW_TERMINAL_STATES = {
    WorkflowState.COMPLETED,
    WorkflowState.FAILED,
    WorkflowState.CANCELLED,
    WorkflowState.SUPERSEDED,
}

TASK_TERMINAL_STATES = {
    TaskState.COMPLETED,
    TaskState.VERIFIED,
    TaskState.FAILED,
    TaskState.CANCELLED,
}
