"""
Controlled vocabulary for Undertrial Liberty Sentinel.

These enums are the single source of truth for every status/type value
used across the domain models, agents, and API. Nothing in this system
should use a raw string literal for a status that has an enum here.

IMPORTANT SAFETY NOTE:
None of these values represent a legal conclusion, a prediction, or a
determination of entitlement. They represent operational/administrative
tracking states only. See docs/domain-model.md for the full rationale.
"""
from enum import Enum


class VerificationStatus(str, Enum):
    """Epistemic status of any piece of information in the system."""
    SOURCE_FACT = "SOURCE_FACT"                # Directly stated in an ingested source document
    USER_REPORTED = "USER_REPORTED"            # Entered by an authorized human user, not yet verified
    SYSTEM_DERIVED = "SYSTEM_DERIVED"          # Calculated from other known facts (no legal rules invented)
    UNVERIFIED = "UNVERIFIED"                  # Present but not confirmed against a source
    CONFLICTING = "CONFLICTING"                # Two or more sources disagree
    UNKNOWN = "UNKNOWN"                        # Not enough information exists
    REQUIRES_HUMAN_REVIEW = "REQUIRES_HUMAN_REVIEW"


class CustodyEventType(str, Enum):
    ARREST_RECORDED = "ARREST_RECORDED"
    CUSTODY_STARTED = "CUSTODY_STARTED"
    REMAND_ORDER = "REMAND_ORDER"
    CUSTODY_EXTENDED = "CUSTODY_EXTENDED"
    JUDICIAL_CUSTODY = "JUDICIAL_CUSTODY"
    POLICE_CUSTODY = "POLICE_CUSTODY"
    TRANSFER = "TRANSFER"
    PRODUCTION = "PRODUCTION"
    COURT_APPEARANCE = "COURT_APPEARANCE"
    RELEASE_ORDER_RECORDED = "RELEASE_ORDER_RECORDED"
    RELEASE_RECORDED = "RELEASE_RECORDED"
    CUSTODY_STATUS_UPDATED = "CUSTODY_STATUS_UPDATED"
    UNKNOWN_CUSTODY_EVENT = "UNKNOWN_CUSTODY_EVENT"


class CurrentCustodyStatus(str, Enum):
    """
    The system's own summary label for 'what do we currently believe about
    custody', NEVER a legal determination of lawful/unlawful detention.
    """
    CUSTODY_STATE_KNOWN_VERIFIED = "CUSTODY_STATE_KNOWN_VERIFIED"
    CUSTODY_STATE_KNOWN_UNVERIFIED = "CUSTODY_STATE_KNOWN_UNVERIFIED"
    CUSTODY_STATE_CONFLICTING = "CUSTODY_STATE_CONFLICTING"
    CUSTODY_STATE_UNKNOWN = "CUSTODY_STATE_UNKNOWN"


class DateType(str, Enum):
    SOURCE_EXPLICIT_DATE = "SOURCE_EXPLICIT_DATE"
    SOURCE_RELATIVE_DATE = "SOURCE_RELATIVE_DATE"
    USER_ENTERED_DATE = "USER_ENTERED_DATE"
    SYSTEM_DERIVED_DATE = "SYSTEM_DERIVED_DATE"
    UNKNOWN_DATE = "UNKNOWN_DATE"


class HearingStatus(str, Enum):
    SCHEDULED = "SCHEDULED"
    HELD_RESULT_RECORDED = "HELD_RESULT_RECORDED"
    HELD_RESULT_MISSING = "HELD_RESULT_MISSING"
    ADJOURNED = "ADJOURNED"
    STATUS_UNKNOWN = "STATUS_UNKNOWN"


class OrderStatus(str, Enum):
    ORDER_ISSUED = "ORDER_ISSUED"
    ORDER_MODIFIED = "ORDER_MODIFIED"
    ORDER_CLARIFIED = "ORDER_CLARIFIED"
    ORDER_SUPERSEDED = "ORDER_SUPERSEDED"
    ORDER_UNKNOWN_STATUS = "ORDER_UNKNOWN_STATUS"


class BailEventType(str, Enum):
    BAIL_APPLICATION_RECORDED = "BAIL_APPLICATION_RECORDED"
    BAIL_HEARING_SCHEDULED = "BAIL_HEARING_SCHEDULED"
    BAIL_ORDER_RECORDED = "BAIL_ORDER_RECORDED"
    BAIL_APPLICATION_WITHDRAWN = "BAIL_APPLICATION_WITHDRAWN"
    BAIL_APPLICATION_DISPOSED = "BAIL_APPLICATION_DISPOSED"
    BAIL_EVENT_UNKNOWN = "BAIL_EVENT_UNKNOWN"


class ReleaseEventType(str, Enum):
    RELEASE_ORDER_RECORDED = "RELEASE_ORDER_RECORDED"
    RELEASE_DOCUMENT_RECEIVED = "RELEASE_DOCUMENT_RECEIVED"
    RELEASE_EVENT_REPORTED = "RELEASE_EVENT_REPORTED"
    RELEASE_VERIFICATION_PENDING = "RELEASE_VERIFICATION_PENDING"
    RELEASE_VERIFIED = "RELEASE_VERIFIED"


class CurrentStatusConfidence(str, Enum):
    """Used specifically to guard against assuming someone is 'currently free'."""
    CURRENT_STATUS_VERIFIED = "CURRENT_STATUS_VERIFIED"
    CURRENT_STATUS_UNVERIFIED = "CURRENT_STATUS_UNVERIFIED"
    CURRENT_STATUS_UNKNOWN = "CURRENT_STATUS_UNKNOWN"


class AttentionCategory(str, Enum):
    UPCOMING_SOURCE_DATE = "UPCOMING_SOURCE_DATE"
    PAST_TRACKED_DATE = "PAST_TRACKED_DATE"
    MISSING_ORDER = "MISSING_ORDER"
    MISSING_CUSTODY_INFORMATION = "MISSING_CUSTODY_INFORMATION"
    CONFLICTING_CUSTODY_INFORMATION = "CONFLICTING_CUSTODY_INFORMATION"
    UNVERIFIED_RELEASE_EVENT = "UNVERIFIED_RELEASE_EVENT"
    UNVERIFIED_BAIL_EVENT = "UNVERIFIED_BAIL_EVENT"
    MISSING_HEARING_RESULT = "MISSING_HEARING_RESULT"
    STALE_CASE_STATE = "STALE_CASE_STATE"
    MISSING_DOCUMENT = "MISSING_DOCUMENT"
    DEPENDENCY_BLOCKED = "DEPENDENCY_BLOCKED"
    HUMAN_REVIEW_REQUIRED = "HUMAN_REVIEW_REQUIRED"
    PROVENANCE_GAP = "PROVENANCE_GAP"


class SignalSeverity(str, Enum):
    """Operational attention priority. NOT a measure of legal seriousness."""
    INFO = "INFO"
    ATTENTION = "ATTENTION"
    HIGH_ATTENTION = "HIGH_ATTENTION"
    REQUIRES_HUMAN_REVIEW = "REQUIRES_HUMAN_REVIEW"


class SignalStatus(str, Enum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"
    DISMISSED_BY_REVIEWER = "DISMISSED_BY_REVIEWER"


class ProceduralEventType(str, Enum):
    FILING_EVENT = "FILING_EVENT"
    LEGAL_AID_REQUEST = "LEGAL_AID_REQUEST"
    COURT_DIRECTION = "COURT_DIRECTION"
    ADJOURNMENT = "ADJOURNMENT"
    PRISON_COMMUNICATION = "PRISON_COMMUNICATION"
    OTHER_PROCEDURAL_EVENT = "OTHER_PROCEDURAL_EVENT"


class DocumentType(str, Enum):
    ARREST_RECORD = "ARREST_RECORD"
    REMAND_ORDER = "REMAND_ORDER"
    BAIL_APPLICATION = "BAIL_APPLICATION"
    BAIL_ORDER = "BAIL_ORDER"
    HEARING_NOTICE = "HEARING_NOTICE"
    COURT_ORDER = "COURT_ORDER"
    RELEASE_ORDER = "RELEASE_ORDER"
    PRODUCTION_WARRANT = "PRODUCTION_WARRANT"
    LEGAL_AID_DOCUMENT = "LEGAL_AID_DOCUMENT"
    OTHER = "OTHER"


class DocumentStatus(str, Enum):
    UPLOADED = "UPLOADED"
    QUARANTINED = "QUARANTINED"
    PARSED = "PARSED"
    PARSE_FAILED = "PARSE_FAILED"
    REJECTED = "REJECTED"


class ExtractionMethod(str, Enum):
    PDF_TEXT_EXTRACTION = "PDF_TEXT_EXTRACTION"
    DOCX_TEXT_EXTRACTION = "DOCX_TEXT_EXTRACTION"
    PLAIN_TEXT = "PLAIN_TEXT"
    JSON_STRUCTURED = "JSON_STRUCTURED"
    CSV_STRUCTURED = "CSV_STRUCTURED"
    USER_MANUAL_ENTRY = "USER_MANUAL_ENTRY"
    UNKNOWN = "UNKNOWN"


class DependencyType(str, Enum):
    DOCUMENT_TO_EVENT = "DOCUMENT_TO_EVENT"
    EVENT_TO_CUSTODY_STATE = "EVENT_TO_CUSTODY_STATE"
    CUSTODY_STATE_TO_HEARING = "CUSTODY_STATE_TO_HEARING"
    HEARING_TO_ORDER = "HEARING_TO_ORDER"
    ORDER_TO_ATTENTION_ITEM = "ORDER_TO_ATTENTION_ITEM"
    ORDER_TO_EVENT = "ORDER_TO_EVENT"
    EVENT_TO_HEARING = "EVENT_TO_HEARING"
    DOCUMENT_TO_ORDER = "DOCUMENT_TO_ORDER"
    BAIL_EVENT_TO_HEARING = "BAIL_EVENT_TO_HEARING"
    ORDER_TO_RELEASE_EVENT = "ORDER_TO_RELEASE_EVENT"
    DOCUMENT_TO_CONFLICT = "DOCUMENT_TO_CONFLICT"


class DependencyStatus(str, Enum):
    SATISFIED = "SATISFIED"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"


class ReviewTaskType(str, Enum):
    CUSTODY_STATE_CORRECTION = "CUSTODY_STATE_CORRECTION"
    CONFLICT_RESOLUTION = "CONFLICT_RESOLUTION"
    VERIFICATION_STATUS_CHANGE = "VERIFICATION_STATUS_CHANGE"
    RELEASE_VERIFICATION = "RELEASE_VERIFICATION"
    ORDER_INTERPRETATION = "ORDER_INTERPRETATION"
    EVENT_CORRECTION = "EVENT_CORRECTION"
    SENSITIVE_DATA_ACCESS = "SENSITIVE_DATA_ACCESS"
    EXPORT_APPROVAL = "EXPORT_APPROVAL"


class ReviewTaskStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ConflictStatus(str, Enum):
    OPEN = "OPEN"
    UNDER_REVIEW = "UNDER_REVIEW"
    RESOLVED_BY_HUMAN = "RESOLVED_BY_HUMAN"


class UserRole(str, Enum):
    CITIZEN = "CITIZEN"
    LEGAL_AID = "LEGAL_AID"
    ADVOCATE = "ADVOCATE"
    ADMIN = "ADMIN"


class AuditAction(str, Enum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    VIEW = "VIEW"
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    EXPORT = "EXPORT"
    SIMULATE = "SIMULATE"
    CRASH_TEST = "CRASH_TEST"
