"""
Central enumerations for the Evidence Dependency Engine.

These enums encode the domain's explicit uncertainty model. The system
must never silently upgrade uncertain states into certain ones -- every
status here is meant to be shown to a human reviewer verbatim.
"""
from enum import Enum


class EvidenceState(str, Enum):
    UNKNOWN = "UNKNOWN"
    USER_REPORTED = "USER_REPORTED"
    DOCUMENT_SUPPORTED = "DOCUMENT_SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    SUPPORTED = "SUPPORTED"
    CONTRADICTED = "CONTRADICTED"
    CONFLICTING = "CONFLICTING"
    UNVERIFIED = "UNVERIFIED"
    SUPERSEDED = "SUPERSEDED"
    EXCLUDED = "EXCLUDED"
    MISSING = "MISSING"
    REQUIRES_HUMAN_REVIEW = "REQUIRES_HUMAN_REVIEW"


class RelationshipType(str, Enum):
    SUPPORTS = "SUPPORTS"
    PARTIALLY_SUPPORTS = "PARTIALLY_SUPPORTS"
    CONTRADICTS = "CONTRADICTS"
    QUALIFIES = "QUALIFIES"
    CORROBORATES = "CORROBORATES"
    DUPLICATES = "DUPLICATES"
    DEPENDS_ON = "DEPENDS_ON"
    DERIVED_FROM = "DERIVED_FROM"
    SUPERSEDES = "SUPERSEDES"
    SUPERSEDED_BY = "SUPERSEDED_BY"
    REQUIRES = "REQUIRES"
    RELATED_TO = "RELATED_TO"
    UNKNOWN_RELATIONSHIP = "UNKNOWN_RELATIONSHIP"


class SupportKind(str, Enum):
    DIRECT_SUPPORT = "DIRECT_SUPPORT"
    CORROBORATIVE_SUPPORT = "CORROBORATIVE_SUPPORT"
    DUPLICATIVE_SUPPORT = "DUPLICATIVE_SUPPORT"
    CONFLICTING_SUPPORT = "CONFLICTING_SUPPORT"


class VerificationStatus(str, Enum):
    UNVERIFIED = "UNVERIFIED"
    PENDING_REVIEW = "PENDING_REVIEW"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    REQUIRES_HUMAN_REVIEW = "REQUIRES_HUMAN_REVIEW"


class NodeType(str, Enum):
    EVIDENCE = "EVIDENCE"
    CLAIM = "CLAIM"
    ISSUE = "ISSUE"


class ReviewActionType(str, Enum):
    EXCLUDE_EVIDENCE = "EXCLUDE_EVIDENCE"
    CHANGE_VERIFIED_STATUS = "CHANGE_VERIFIED_STATUS"
    RESOLVE_CONTRADICTION = "RESOLVE_CONTRADICTION"
    APPROVE_RELATIONSHIP = "APPROVE_RELATIONSHIP"
    MODIFY_CLAIM = "MODIFY_CLAIM"
    APPROVE_ISSUE_MAPPING = "APPROVE_ISSUE_MAPPING"
    PUBLISH_EXPORT = "PUBLISH_EXPORT"
    OTHER_CONSEQUENTIAL_ACTION = "OTHER_CONSEQUENTIAL_ACTION"


class ReviewStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class UserRole(str, Enum):
    CITIZEN = "CITIZEN"
    LEGAL_AID = "LEGAL_AID"
    ADVOCATE = "ADVOCATE"
    ADMIN = "ADMIN"


class CrashTestEventType(str, Enum):
    REMOVE_EVIDENCE = "REMOVE_EVIDENCE"
    EXCLUDE_EVIDENCE = "EXCLUDE_EVIDENCE"
    MARK_UNVERIFIED = "MARK_UNVERIFIED"
    REVERSE_RELATIONSHIP = "REVERSE_RELATIONSHIP"
    INTRODUCE_CONTRADICTORY_EVIDENCE = "INTRODUCE_CONTRADICTORY_EVIDENCE"
    SUPERSEDE_DOCUMENT = "SUPERSEDE_DOCUMENT"
    REMOVE_SOURCE_DOCUMENT = "REMOVE_SOURCE_DOCUMENT"
    INVALIDATE_PROVENANCE = "INVALIDATE_PROVENANCE"
    BREAK_CLAIM_DEPENDENCY = "BREAK_CLAIM_DEPENDENCY"
    CREATE_MISSING_EVIDENCE = "CREATE_MISSING_EVIDENCE"


class CriticalityLevel(str, Enum):
    NONE = "NONE"
    LOW = "LOW"
    MODERATE = "MODERATE"
    SINGLE_POINT_DEPENDENCY = "SINGLE_POINT_DEPENDENCY"


class EvaluationResult(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    NOT_RUN = "NOT_RUN"
